### ISSUE TITLE
City 테이블 데이터 세팅

### ISSUE THREAD

**Issue by jjongwa** [woowacourse-teams/2023-hang-log#10]
### 📄 Describe

여행 생성 시 입력받는 도시 이름들에 대한 초기 데이터를 저장해 놓아야 합니다.
어떤 api를 사용해 도시 정보를 추출할 건지 아직 확정되지 않음

### ✅ Tasks

- [x] 사용할 api 정하기
- [x] 데이터에서 필요한 정보(도시 이름, 대륙...?) 추출
- [x] City 테이블에 기본 데이터 세팅

### 🙋🏻 More

백엔드만 무려 다섯명인데
설~ 마 아무도 안하겠어?
나다~  싶으면 해야겠지?
