### ISSUE TITLE
로깅 구현

### ISSUE THREAD

**Issue by mcodnjs** [woowacourse-teams/2023-hang-log#115]
### 📄 Describe

로깅합시다 로깅!
어떤 라이브러리로 어떤 에러를 로깅할건지 등등을 정해봅시다

### ✅ Tasks

- [ ] 로깅 라이브러리 선정
- [ ] 어떤 에러까지 로깅할건지
- [ ] 어떤 단위로 파일을 관리할건지
