### ISSUE TITLE
도시 검색 기능 특수문자 작성시 버그 수정 + 검색어와 매칭되는 제안도시가 하나일 시 엔터로 적용가능

### ISSUE THREAD

**Issue by Dahyeeee** [woowacourse-teams/2023-hang-log#121]
### 🔨 Describe

도시 검색시 특수문자를 입력하면 버그 발생 => 정규표현식때문

검색어와 매칭되는 제안 단어가 하나일 시 엔터로 도시테그 적용가능하게 수정필요

### ✅ Tasks

- [x] 도시 검색 특수문자 입력해도 버그 발생하지 않도록 수정
- [x] 검색어와 매칭되는 제안 단어 하나일 시 엔터로 도시태그 선택가능하게 수정 
- [x] 이전에 inputfocusedindex가 남아있어서 검색어결과가 없을 때 enter를 쳐도 이전 도시가 태그로 적용되는 버그 수정
- [x] 새로운 도시 입력해도 focusedIndex가 남아있는 버그 수정
- [x] 검색어 없을 시 제안 목록 나오지 않도록 수정
- [x] esc 클릭시 제안목록 닫히는 기능
