### ISSUE TITLE
Jacoco통한 테스트 커버리지 측정 및 자동화 설정

### ISSUE THREAD

**Issue by jjongwa** [woowacourse-teams/2023-hang-log#130]
### 🤔 Describe

Pr이 merge되기 전 코드 정적 분석을 통해 테스트 작성을 강요
-> 조금 더 짜임새있는 코드를 만들 수 있지 않을까 
하는 생각이 들어 적용해 보려고 합니다.

### ✅ Tasks

- [x] Gradle에 Jacoco 추가
- [x] ~Codecov 적용~ organization 계정으로 인증이 필요해 취소
- [x] GitHub Action Workflow 설정

### 🙋🏻 More

하나 둘 셋
파이리
