### ISSUE TITLE
경비 조회기능 구현

### ISSUE THREAD

**Issue by waterricecake** [woowacourse-teams/2023-hang-log#135]
### 📄 Describe

경비 조회 시
- 총 경비
- 카테고리별 총 금액 및 퍼센트(카테고리 금액/총금액*100)
- 사용하는 환율
- 날짜별 총 금액
을 계산하여 보내줌

### ✅ Tasks

- [x] 총 경비 계산
- [x] 카테고리별 총 금액 및 퍼센트 계산
- [x] 사용하는 환율 분류
- [x] 날짜별 총 금액 계산
