### ISSUE TITLE
Trip 관련 API 리팩토링

### ISSUE THREAD

**Issue by mcodnjs** [woowacourse-teams/2023-hang-log#136]
### 🔨 Describe

1. Trip 전체 조회와 단일 조회 API 명세에 cities 필드가 추가되었습니다.
2. Trip 전체 조회 API에서 DayLog 리스트를 제외합니다.
3. Trip 단일 여행 수정 API에서 imageUrl을 추가합니다.

### ✅ Tasks

- [x] Trip 전체 조회, 단일 조회 API에 cities 필드 추가
- [x] Trip 전체 조회 API에서 DayLog 리스트 제외
- [x]  Trip 단일 여행 수정 API imageUrl 추가
