### ISSUE TITLE
TripsPage 리팩토링

### ISSUE THREAD

**Issue by ashleysyheo** [woowacourse-teams/2023-hang-log#142]
### 🔨 Describe

- 경로 제대로된 절대경로로 수정 
- semantic 태그 사용
- 네이밍 수정
- css viewport width 줄일 시 이미지 비율 깨지는 문제 해결 
- 기타 버그 수정

### ✅ Tasks

- [ ] 경로 수정
- [ ] `div` semantic 태그로 변경
- [ ] viewport width를 줄일 시 이미지 비율이 그대로 변경된다
- [ ] 기타 버그 수정
