### ISSUE TITLE
TripEditPage 리팩토링

### ISSUE THREAD

**Issue by ashleysyheo** [woowacourse-teams/2023-hang-log#152]
### 🔨 Describe

- 경로 제대로된 절대경로로 수정  
- semantic 태그 사용 
- 네이밍 수정 
- 기타 버그 수정 
- TripItem 내부 드래그 로직 커스텀 훅으로 분리 

### ✅ Tasks

- [ ] 경로 수정 
- [ ] `div` > semantic 태그로 변경 
- [ ] `useDraggedItem` 커스텀 훅 생성 
- [ ] 기타 버그 수정
