### ISSUE TITLE
지도 기능 구현

### ISSUE THREAD

**Issue by ashleysyheo** [woowacourse-teams/2023-hang-log#165]
### 📄 Describe

![Trip Edit Page](https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/f5e597d6-3f90-4276-9215-d176aa68e9c7)

<br>

TripEditPage/TripPage에서 장소 좌표 및 이동 경로를 볼 수 있는 지도 기능을 구현한다. 

### ✅ Tasks

- [ ] 지도 불러오기
- [ ] 지도에 `장소` 아이템들 좌표 표시
- [ ] 아이템 ordinal 순서대로 좌표를 점선으로 연결하기
- [ ] 왼쪽에서 아이템 스크롤 시 가장 목록의 가장 상단에 있는 장소의 위치를 포커스 시키기
