### ISSUE TITLE
Item생성시 Place Category를 가져오는 기능구현

### ISSUE THREAD

**Issue by hgo641** [woowacourse-teams/2023-hang-log#215]
### 📄 Describe

`Item`생성또는 수정 요청이 올 때, 
`PlaceRequest`가 존재한다면, `PlaceRequest`의 `apiCategory`필드를 보고 `Place`에 올바른 `Category`를 설정해줍니다.

### ✅ Tasks

* [x] PlaceRequest의 `List<String> apiCategory`에서 Category의 `engName`을 찾는다.
* [x] `engName`을 통해 `CategoryRepository`에서 `Category`객체를 찾아온다.
* [x] 찾아온 `Cateogory`객체를 새로운 `Place`객체에 할당한다.

### 예외처리
* [x] `apiCategory`필드에 적절한 `engName`이 존재하지 않으면 예외 발생
* [x] 요청한 `engName`을 가지는 `Category`가 DB에 존재하지 않을 때 예외 발생

### 🙋🏻 More

홍고 렛츠고!
