### ISSUE TITLE
Item관련 필드 수정

### ISSUE THREAD

**Issue by hgo641** [woowacourse-teams/2023-hang-log#22]
### 🔨 Describe

`Item`과 관련된 필드를 수정합니다.

### ✅ Tasks

* [x] [Item] imageUrls 필드 추가
    * [ItemDto]  imageUrls 필드 추가
* [x] [Item] raiting validation 추가
* [x] [PlaceRequest] 위도, 경도 validation 추가
* [x] [PlaceRequest] apiCategory필드를 리스트로 수정
* [x] [Expense] amount 타입을 Double로 변경
