### ISSUE TITLE
Trip image 관련 로직 수정, item image 최대 수 제한 변경

### ISSUE THREAD

**Issue by LJW25** [woowacourse-teams/2023-hang-log#248]
### 🔨 Describe

제곧내

### ✅ Tasks

- [x] Trip update시 imageUrl -> imageName 파싱 추가
- [x] Trip 조회 시 imageName -> imageUrl 파싱 추가
- [x] 아이템 개수 최대 제한 변경

### 🙋🏻 More

룰루
