### ISSUE TITLE
Rating nullable로 변경 및 최소제한해제

### ISSUE THREAD

**Issue by hgo641** [woowacourse-teams/2023-hang-log#253]
### 🔨 Describe

Raiting 최소 제한 제거
Rating null 검증 추가
Place & Expense cascade Merge 추가

### ✅ Tasks

* [x] Rating nullable하게 변경
* [x] Rating의 @DecimalMin(0.5) 삭제
* [x] Place & Expense cascade Merge 추가
### 🙋🏻 More

아자!!
