### ISSUE TITLE
trip생성페이지 구현 

### ISSUE THREAD

**Issue by Dahyeeee** [woowacourse-teams/2023-hang-log#33]
### 📄 Describe

새로운 trip을 생성하는 페이지를 구현

### ✅ Tasks

- [ ] 화면 오른쪽 하단에 이미지 넣기

- [x] 방문도시 입력 받을 수 있는 입력창 만들기
- [x] 검색어에 따라 도시 제안 목록 보여주기
- [x] 검색어에 제안 목록이 없을 경우 대체 텍스트 보여주기
- [x] 클릭하면 도시 태그 생성
- [x] 똑같은 도시 입력시, 태그 제일 뒤로 보내기
- [x] 태그 삭제가능
- [x] 키보드 up, down 입력으로 제안목록 왔다갔다하기
- [ ] 도시 15개 이상으로 입력 불가 => 경고문구 출력
- [ ] 제안 목록 키보드로 조작시 자동스크롤링 기능

- [ ] 방문 기간 입력 받을 수 있는 입력창 만들기

- [ ] 기록하기 버튼을 클릭하면 서버에 post 요청 보내기
- [ ] 입력이 없을 시 버튼 비활성화? 경고메세지?

### 🙋🏻 More
- 도시 입력 최대 몇개까지? 15개
