### ISSUE TITLE
공유 기능 구현

### ISSUE THREAD

**Issue by waterricecake** [woowacourse-teams/2023-hang-log#392]
### 📄 Describe

여행을 공유하는 기능을 구현합니다.
여행에서 공유 가능 상태를 변경할 수 있어야 하고
공유 가능 시 공유 url을 조회할 수 있어야 하고
공유된 여행 페이지를 조회할 수 있어야 합니다.

### ✅ Tasks

- [ ] 여행 조회 api에 공유 상태를 포함한다
- [ ] 여행 공유 상태를 수정할 수 있다
- [ ] 여행 공유 url을 조회 할 수 있다
- [ ] 여행 공유 페이지를 조회 할 수 있다
