### ISSUE TITLE
Trip 테스트 추가 

### ISSUE THREAD

**Issue by mcodnjs** [woowacourse-teams/2023-hang-log#401]
### 🔨 Describe

Mock의 문제점과 부족한 테스트를 보완합니다.

### ✅ Tasks

- [ ] 컨트롤러 통합 테스트
- [ ] 컨트롤러 슬라이스 테스트 (DTO 검증)
- [ ] mock 없이 jpa를 이용한 서비스 테스트
