### ISSUE TITLE
TripItem 추가/수정 모달 구현

### ISSUE THREAD

**Issue by ashleysyheo** [woowacourse-teams/2023-hang-log#52]
### 📄 Describe

<img width="1512" alt="Trip Item Add Modal - non spot-1" src="https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/c4dbcbc3-5946-4851-a745-f06138aba3ce">
<img width="1512" alt="Trip Item Add Modal - non spot-2" src="https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/903e3010-6247-4d90-a918-01728cfccb5d">

<br>

TripItem 추가/수정 모달 구현

### ✅ Tasks

- [ ] 카테고리, 날짜, 제목을 필수로 입력해야 한다. 
  - [ ] 날짜는 모달 생성을 클릭한 탭의 날짜가 디폴트로 설정된다.
  - [ ] 카테고리 `장소` 선택 시 제목은 구글 map api를 사용해서 검색 결과 확인 및 자동완성을 할 수 있다. 
  - [ ] 카테코리 `기타` 선택 시 제목은 사용자가 입력한 값이 된다. 
- [ ] 옵셔널로는 별점, 비용 (카테고리, 통화, 금액), 메모, 사진을 입력할 수 있다. 
  - [ ] 비용 카테고리 디폴트는 `기타`, 통화 디폴트는 `₩(원)`이다. 
- [ ] 사진은 최대 5장 업로드할 수 있다. 
- [ ] 일정 추가/수정 성공 시 성공했다는 토스트 메세지를 볼 수 있다.
