### ISSUE TITLE
공유 여행 soft delete 및 비공유 상태시 sharedCode 전송 해결

### ISSUE THREAD

**Issue by waterricecake** [woowacourse-teams/2023-hang-log#520]
### 📄 Describe

1. 여행 삭제 시 soft delete를 통해 제거한다
2. 비공유 상태 시 sharedCode가 null이 아니고 전송이 되는 버그

### ✅ Tasks

- [x] baseEntity 상속 및 soft delete 추가
- [x] 삭제 상태 객체 참조 불가
- [x] 비공유 상태 sharedCode 조회시 null값 반영
