### ISSUE TITLE
trip 추가 페이지 날짜 선택 컴포넌트 구현

### ISSUE THREAD

**Issue by Dahyeeee** [woowacourse-teams/2023-hang-log#53]
### 📄 Describe

trip 추가 페이지 날짜 선택 컴포넌트 구현

### ✅ Tasks

- [x] 인풋 창 클릭시 달력 컴포넌트 출력
- [x] 인풋 창에 직접 입력 불가능
- [x] 선택한 날짜가 텍스트로 인풋창에 자동으로 입력
- [x] 60일 이상 선택 불가능
