### ISSUE TITLE
Flyway v8 : sharedStatus Trip으로 이동

### ISSUE THREAD

**Issue by LJW25** [woowacourse-teams/2023-hang-log#638]
### 🔨 Describe

기존 DB 구조의 sharedStatus를 SharedTrip에서 Trip으로 이동합니다.

### ✅ Tasks

- [x] Trip에 SharedStatus 컬럼 추가
- [x] SharedTrip 백업 테이블 임시 생성 
- [x] Trip에 저장된 여행들에 sharedStatus 적용
- [x] SharedTrip에서 SharedStatus 컬럼 삭제
- [ ] 임시 백업 테이블 삭제

- [x] 변경된 구조에 맞게 프로덕션 코드 수정

### 🙋🏻 More

해 보겠습니다?

**Comment by jjongwa** [comment]
응원합니다
