### ISSUE TITLE
커뮤니티 페이지 트립 아이템 작성자 추가

### ISSUE THREAD

**Issue by Dahyeeee** [woowacourse-teams/2023-hang-log#641]
### 🔨 Describe

커뮤니티 페이지에 트립 아이템 작성자가 누락됨 

### ✅ Tasks

- [ ] 커뮤니티 페이지 트립 아이템 작성자 추가
- [ ] 커뮤니티 페이지 스타일 변경
- [ ] 커뮤니티 페이지 로그인 상태 입력받기
