### ISSUE TITLE
여행 생성 및 여행 상세 조회 쿼리 개선

### ISSUE THREAD

**Issue by jjongwa** [woowacourse-teams/2023-hang-log#645]
### 🔨 Describe

현재 최악의 경우 
- 여행 생성: 110개 쿼리 발생 ->  4개로 줄이는게 목표
- 단일 여행 상세 조회: 3,882개 쿼리 발생 -> 5개로 줄이는게 목표

### ✅ Tasks

- [x] 여행 생성 
    - [x] saveAll 문제 해결
    - [x] tripCity 쪽 쿼리 개선
- [x] 여행 상세 조회
    - [x] 아이템 조회 N+1문제 해결
    - [x] daylog, item, city 한꺼번에 조회하도록 조인 쿼리 작성

### 🙋🏻 More

홍박사님과 함께하는 추석 특집 이벤트
