### ISSUE TITLE
스프링 이벤트를 사용한 S3 이미지 파일 삭제

### ISSUE THREAD

**Issue by jjongwa** [woowacourse-teams/2023-hang-log#646]
### 📄 Describe

#323 
현재 이미지를 삭제하는 로직이 존재하지 않고 단순 Url 변경만 하고 있기 때문에 쓰이지 않는 이미지 파일들이 S3 저장소에 쌓이고 있는 상태입니다. 
이를 해결하기 위해 스프링 이벤트를 사용한 삭제 로직을 구현합니다.

현재 이미지를 사용하는 곳은 총 세 군데 입니다.
- 프로필 사진 변경 -> Member
- 여행 대표사진 변경 -> Trip
- 아이템 이미지 변경 -> Item

이 세 곳에서 동일한 이벤트를 사용하여 클래스 간의 결합도를 낮추고 
코드의 재사용성을 늘립니다.

또한 트랜잭션을 분리하여 도메인 객체의 변경과 이미지 파일 삭제 간의 사이클을 분리하고,
조금 더 빠른 처리속도를 제공하도록 합니다.
(ex. S3로 파일 삭제 요청을 보내는 작업이 실패하더라도 기존과 같이 이미지 변경은 이루어져야 함)

### ✅ Tasks

- [ ] 이미지 삭제 로직 구현
- [ ] 이미지 이벤트 생성
- [ ] 이미지 이벤트 리스너 만들어 삭제 로직 이관

### 🙋🏻 More

근데 보니까 이미지 등록/수정할 때 ImageUrlConverter라는걸 쓰던데,
컴포넌트이면서 util 패키지에 있고 스태틱 메서드라 여기저기서 갖다 쓰는 바람에
의존성이 박살나 있더라구요. 그거 먼저 필수로 고쳐야 할 듯
