### ISSUE TITLE
도시입력창 & 제안목록 컴포넌트 수정

### ISSUE THREAD

**Issue by ashleysyheo** [woowacourse-teams/2023-hang-log#65]
### 🔨 Describe

<img width="340" alt="Screenshot 2023-07-18 at 11 32 23 AM" src="https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/f840f869-d22c-405d-98a2-f3577a3cb85b">

![image](https://github.com/woowacourse-teams/2023-hang-log/assets/102305630/27221d04-28ec-40a1-9fbd-3972d6e88582)

<br>

- 도시입력창 포커스 시 백그라운드 컬러가 회색이 아닌 흰색으로 변경되고, box-shadow가 추가된다 
- 핀 아이콘 사이즈 및 stroke-width 수정
- 하단, 검색결과 창에 box-shadow 추가
- 인풋 창이 포커스 되었을 때 포커스 아웃라인을 없앤다

<br>
<br>

![image](https://github.com/woowacourse-teams/2023-hang-log/assets/102305630/f04d2b2c-db8b-4b0b-ac7c-6e8d6bd23d72)

<br>

- 검색 결과가 많을 경우 height가 변하지 않고 스크롤 할 수 있도록 변경한다. 

### ✅ Tasks

- [x] 검색 창 `backgroundColor: white`
- [x] 검색 창 `boxShadow` 추가
- [x] 핀 아이콘 `width`, `height`, `storkeWidth` 수정
- [x] 검색창 결과 박스에 `boxShadow` 추가
- [x] 인풋 창 포커스 시 포커스 아웃라인 제거 
- [x] 검색 결과 늘어날 시 박스 사이즈가 변하지 않고 스크롤로 변경
