### ISSUE TITLE
UI 변경사항 적용

### ISSUE THREAD

**Issue by Dahyeeee** [woowacourse-teams/2023-hang-log#681]
### 🔨 Describe

UI적으로 불편하거나 변경되었으면 좋겠는 사항 논의 후 반영

### ✅ Tasks

- [x] 모달창 백드롭 클릭시 닫히지 않게 함(itemaddmodal)
- [x] 커뮤니티페이지에서 여행 설명 줄바꿈 적용
- [x] 여행정보수정모달 완료시 변경사항 바로 UI에 반영되도록 변경
- [x] 여행정보수정모달 사전 업로드 시 변경버튼 클릭안되도록 변경 
- [x] 모바일에서 모달창 '확인'버튼 항상 화면에 나오도록 변경 
- [x] 커뮤니티 트립 페이지에서 내 여행일 시, 여행수정하기 버튼 생성 ( 여행수정페이지로 이동)
