### ISSUE TITLE
단일 여행 정보 수정 모달 구현

### ISSUE THREAD

**Issue by ashleysyheo** [woowacourse-teams/2023-hang-log#69]
### 📄 Describe

<img width="1512" alt="Trip Edit Page" src="https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/48f5dfe7-d3a2-445d-aec2-b18b56298b17">

<br>

여행의 정보를 수정할 수 있는 모달을 구현한다. 

### ✅ Tasks

- [ ] 여행 생성 페이지에서 입력된 정보가 적혀있다
- [ ] 도시를 추가/삭제 할 수 있다
- [ ] 일정 기간을 수정할 수 있다 
  - [ ] 수정된 여행 기간이 현재 설정된 기간보다 작을 경우 에러 모달을 볼 수 있다 
- [ ] 여행 제목을 입력할 수 있다
- [ ] 여행 정보를 입력할 수 있다
- [ ] 여행 대표 이미지를 설정할 수 있다 (옵셔널)

- [ ] 여행수정 페이지로 바로 들어갔을 때 도시목록(서버통신)없는  오류 수정
