### ISSUE TITLE
단일 여행 조회 및 경비 조회 api 개선

### ISSUE THREAD

**Issue by waterricecake** [woowacourse-teams/2023-hang-log#692]
### 🔨 Describe

단일 여행 조회 및 경비 조회 api 개선

1. 공유된 단일 여행 조회 api 개선

      기존 : 6번

      - sharedtrip 조회 (3번)
      - trip 조회 (2번)
      - city 조회

      개선 : 3번
      - sharedtrip 조회
      - trip 조회
      - city 조회

2. 공개된 단일 여행 조회 api 개선

      기존 : 9번

      - 토큰 확인
      - trip 조회
      - trip 조회
      - publishedTrip 공개 날짜 조회
      - 좋아요 갯수 조회
      - 좋아요 조회 (멤버가 좋아하는지)
      - 도시 조회
      - 도시 조회 (tripCity가 city 참조)
      - member (trip이 member 참조) 조회
      
      개선 : 5번
      - 로그인
      - trip 조회
      - 도시 조회
      - publishedTrip 조회
      - 좋아요 갯수 및 좋아요 여부 조회

3. 경비 조회 api 개선

     기존 : 7 ~ 6
     - 토큰 확인
     - 본인 여행 확인
     - 여행 조회
     - 환율 조회 (날짜로 부터 가장 최신값)
        - 실패시 : 환율 조회 (가장 오래된 값)
     - 카테고리 목록 조회
     - 도시 조회

      개선 : 5
      - 토큰 확인
      - 본인 여행 확인
      - 여행조회
      - 환율 조회 ( 날짜로 부터 가장 최신값)
      - 도시 조회

4. 공유된 여행 경비 조회 api 개선

      기존 : 6 ~ 5
      - 공유여행 조회
      - 여행 조회
      - 환율 조회 ( 날짜로 부터 가장 최신값)
          - 실패시 : 환율 조회 ( 가장 오래된 값)
      - 카테고리 목록 조회
      - 도시 조회

      개선 : 4
      - 공유여행 조회
      - 여행 조회
      - 환율 조회 ( 날짜로 부터 가장 최신값)
      - 도시 조회

5. 공개된 여행 경비 조회 api 개선

     기존 : 5 ~ 4

      - 여행 조회
      - 환율 조회 ( 날짜로 부터 가장 최신값)
          - 실패시 : 환율 조회 ( 가장 오래된 값)
      - 카테고리 목록 조회
      - 도시 조회

      개선 : 4
      - 공유여행 조회
      - 여행 조회
      - 환율 조회 ( 날짜로 부터 가장 최신값)
      - 도시 조회

### ✅ Tasks

- [x] 공유된 단일 여행 조회 api 개선
- [x] 공개된 단일 여행 조회 api 개선
- [x] 경비 조회 api 개선
- [x] 공유된 여행 경비 조회 api 개선
- [x] 공개된 여행 경비 조회 api 개선

### 🙋🏻 More

화이팅....
