### ISSUE TITLE
커뮤니티 전체&추천 여행 목록 조회 쿼리 개선

### ISSUE THREAD

**Issue by mcodnjs** [woowacourse-teams/2023-hang-log#698]
### 커뮤니티 전체&추천 목록 API 쿼리 현황

> 현재 Dev 기준
```
커뮤니티 전체 목록: LoggingForm(apiUrl=/community/trips, apiMethod=GET, queryCounts=57, queryTime=77)
커뮤니티 추천 목록: LoggingForm(apiUrl=/community/recommends, apiMethod=GET, queryCounts=30, queryTime=33)
```

> 쿼리 내역 (3번 항목을 제외하고는 2개의 API가 아래와 같이 조회되고 있음)

1. @Auth refresh token 검사 (1개)
2. Paging Limit(10)개의 published된 여행 조회 (1개)
3. 10개의 SharedTrip 조회 (10개) 
4. 10개의 Trip에 대한 정보 조회 (대략 5*10개 + @)
    1. TripId로 TripCity 가져옴
    2. CityID로 TripCity 개수만큼 City 정보 조회 (n개)
    3. TripId로 Like 개수 조회
    4. 행록 멤버인 경우 해당 Trip을 좋아요 했는지 안했는지 여부
    5. Trip의 멤버 정보 조회

### 개선 

1(`@Auth`) + 3개로 줄일 예정

### ✅ Tasks

- [x] SharedTrip 조회 쿼리 없애기
- [x] Trip 조회 시 Member 정보까지 조회
- [x] TripId들에 대한 City 조회를 1회로 
- [x] TripId들에 대한 좋아요 개수 및 좋아요 여부 조회를 1회로
