### ISSUE TITLE
스케줄링을 통한 데이터 삭제 기능

### ISSUE THREAD

**Issue by jjongwa** [woowacourse-teams/2023-hang-log#742]
### 📄 Describe

멤버 삭제 또는 여행 삭제 등 이벤트 처리한 메서드에서 에러가 발생하면 이를 파악할 수 없는데, 
테이블을 만들어 에러가 발생한 메서드의 정보를 저장하고 
스케줄링을 통해 이를 재시도 하는 로직을 만들어 볼까 합니다.

### ✅ Tasks

- [ ] 에러가 발생한 로직의 memberId or tripId를 저장할 테이블 생성
- [ ] 에러 발생 시 테이블에 데이터 삽입 기능 구현
- [ ] 스케줄링 처리할 기능 구현

### 🙋🏻 More

<img width="594" alt="image" src="https://github.com/woowacourse-teams/2023-hang-log/assets/77482065/41a20dda-3060-4692-a9f7-b085f9db4118">
