### ISSUE TITLE
클래스간 연관관계 레거시 리팩토링

### ISSUE THREAD

**Issue by LJW25** [woowacourse-teams/2023-hang-log#745]
### 🔨 Describe

객체 사이의 관계가 여러번 수정이 되면서 레거시가 있는 듯 해 이를 정리하려 합니다.
일단은 소소한것부터..

현재 객체간 연관관계는 [노션](https://www.notion.so/5791064afdc94edfbae34580ccfa318f?pvs=4)에 정리해뒀으니 참고

### ✅ Tasks

- [x] item -> dayLogs의 `cascade = Persist` 제거
- [x] item → images의 `fetch = LAZY` 제거
- [x] expense → category의 `cascade = Persist` 제거

### 🙋🏻 More

각 항목별 제거하려는 이유
1. item -> dayLogs의 `cascade = Persist` 제거 : 여행이 생성 될 때 이미 데이로그가 생성되므로, 데이로그가 없을 때 아이템이 저장 될 일이 아예 없음. 이런 경우가 생기면 로직상 문제 아닐까요.
2. item → images의 `fetch = LAZY` 제거 : OneToMany관계이기 때문에 default가 LAZY임.
3. expense → category의 `cascade = Persist` 제거 : category는 고정으로 DB에 박혀있기 때문에 persist 필요 없음.

이외에 또 있으면 추가하겠습니다.
