### ISSUE TITLE
새로운 트립 추가 페이지 구현

### ISSUE THREAD

**Issue by Dahyeeee** [woowacourse-teams/2023-hang-log#75]
### 📄 Describe

도시입력과 날짜 입력을 할 수 있는 페이지 구현 

### ✅ Tasks

- [ ] CitySearchBar, DateInput 컴포넌트 합치기
- [ ] citytags와 daterange 정보 가져와서 서버로 post 요청보내기
- [ ] 둘 중 하나라도 입력이 안되었을 시 요청 보내지 못하게 막기(toast? 버튼 비활성화?)
- [ ] 화면 하단 오른쪽에 이미지 넣기
