### ISSUE TITLE
좋아요 수 및 좋아요 변경 이력 캐싱

### ISSUE THREAD

**Issue by jjongwa** [woowacourse-teams/2023-hang-log#751]
### 📄 Describe

현재 게시물의 좋아요 수를 요청할 때 마다 쿼리를 통해 계산해 가져오고 있습니다.
해당 부분을 레디스에 캐싱을 통해 개선해보려 합니다.

또한, 현재 좋아요를 누를 때마다 실시간으로 게시물 좋아요 여부를 변경하는 쿼리가 발생하는데,
이 부분도 캐싱하고, write-back 전략을 적용하여 매 한 시간마다 batch update를 해 정합성을 보장하는 로직으로 변경하려 합니다.

### ✅ Tasks

- [x] 좋아요 변경 이력 캐싱
- [x] 게시물 좋아요 수 캐싱
- [x] 여행 조회에서 좋아요 수와 회원의 좋아요 여부 로직 변경
