### ISSUE TITLE
Transactional Outbox Pattern과 스케줄링을 통한 삭제 이벤트 처리

### ISSUE THREAD

**Issue by mcodnjs** [woowacourse-teams/2023-hang-log#754]
### 🔨 Describe

Transactional Outbox Pattern과 스케줄링을 통한 삭제 이벤트 처리

### ✅ Tasks

- [ ] 이벤트 테이블 생성
- [ ] 발행한 비동기 이벤트를 DB에 저장
- [ ] 스케줄링을 통하여 이벤트 작업 순차 처리
