### ISSUE TITLE
패키지 구조 변경

### ISSUE THREAD

**Issue by LJW25** [woowacourse-teams/2023-hang-log#795]
### 🔨 Describe

기존의 파일 유형에따라 패키지를 나누었던 방식은 프로그램의 규모가 커질수록 변경에 어려움이 있고 패키지간에 중복되는 코드가 많이 발생한다고 느껴져, colocation 방식으로 패키지 구조를 변경합니다.

### ✅ Tasks

- [x] 패키지 구조 변경
- [x] import 규칙 재정의
- [x] 중복 로직 삭제

### 🙋🏻 More

**_진짜 다시 열심히 함._**

**Comment by dladncks1217** [comment]
리더 이오...😮
