### ISSUE TITLE
카테고리 계층화 및 테이블에 데이터 세팅

### ISSUE THREAD

**Issue by jjongwa** [woowacourse-teams/2023-hang-log#9]
### 📄 Describe

Google Map api를 기반으로 한 카테고리들을 타입 별로 나누어 정리 후 Category 테이블에 데이터를 미리 세팅해 놓아야 합니다.

### ✅ Tasks

- [x] Google Map api에서 카테고리 리스트 추출
- [x] 각 카테고리 별 계층화한 id 할당
- [x] 테이블에 초기 데이터 세팅

### 🙋🏻 More

언젠가는 해야 하잖아
누군가는 해야 하잖아
